db.Attendance_DB.insertMany([

    {
        attendance_id:1,
        attendance:false,
        user_id:1,
        topic_id:1,
        task_id:1,
    },
    {
        attendance_id:2,
        attendance:false,
        user_id:2,
        topic_id:2,
        task_id:2,
    },
    {
        attendance_id:3,
        attendance:true,
        user_id:3,
        topic_id:3,
        task_id:3,
    },
    {
        attendance_id:4,
        attendance:true,
        user_id:4,
        topic_id:4,
        task_id:4,
    },
    {
        attendance_id:5,
        attendance:true,
        user_id:5,
        topic_id:5,
        task_id:5,
    },
    {
        attendance_id:6,
        attendance:true,
        user_id:6,
        topic_id:6,
        task_id:6,
    },
    {
        attendance_id:7,
        attendance:false,
        user_id:7,
        topic_id:7,
        task_id:7,
    },
    {
        attendance_id:8,
        attendance:true,
        user_id:8,
        topic_id:8,
        task_id:8,
    },
    {
        attendance_id:9,
        attendance:false,
        user_id:9,
        topic_id:9,
        task_id:9,
    },
    {
        attendance_id:10,
        attendance:true,
        user_id:10,
        topic_id:10,
        task_id:10,
    },

])