// use ("zen_class_DB");


 db.User_DB.insertMany([
 

    {
        "user_id":1,
        "user_name":"saveen",
        "user_mail":"saveen@gmail.com",
        "user_Number":8220123111,
        "user_batchNO":"WE1",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":2,
        "user_name":"kaveen",
        "user_mail":"kaveen@gmail.com",
        "user_Number":8220123222,
        "user_batchNO":"WE2",
        "mentor_id":2,
        "mentor_name": "sathishkumar",
    },
    {
        "user_id":3,
        "user_name":"praveen",
        "user_mail":"praveen@gmail.com",
        "user_Number":8220123333,
        "user_batchNO":"WE3",
        "mentor_id":3,
        "mentor_name": "kumar",
    },
    {
        "user_id":4,
        "user_name":"sibi",
        "user_mail":"sibi@gmail.com",
        "user_Number":8220123444,
        "user_batchNO":"WE4",
        "mentor_id":4,
        "mentor_name": "mayil",
    },
    {
        "user_id":5,
        "user_name":"sibisaveen",
        "user_mail":"sibisaveen@gmail.com",
        "user_Number":8220123555,
        "user_batchNO":"WE5",
        "mentor_id":5,
        "mentor_name": "nandhi",
    },
    {
        "user_id":6,
        "user_name":"ruth",
        "user_mail":"ruth@gmail.com",
        "user_Number":8220123666,
        "user_batchNO":"WE6",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":7,
        "user_name":"santh",
        "user_mail":"santh@gmail.com",
        "user_Number":8220123777,
        "user_batchNO":"WE7",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":8,
        "user_name":"azhar",
        "user_mail":"azhar@gmail.com",
        "user_Number":8220123888,
        "user_batchNO":"WE8",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":9,
        "user_name":"ben",
        "user_mail":"ben@gmail.com",
        "user_Number":8220123999,
        "user_batchNO":"WE9",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":10,
        "user_name":"ruthsaveen",
        "user_mail":"ruthsaveen@gmail.com",
        "user_Number":8220123000,
        "user_batchNO":"WE10",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":11,
        "user_name":"saveen",
        "user_mail":"saveen@gmail.com",
        "user_Number":8220123111,
        "user_batchNO":"WE1",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":12,
        "user_name":"kaveen",
        "user_mail":"kaveen@gmail.com",
        "user_Number":8220123222,
        "user_batchNO":"WE2",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":13,
        "user_name":"praveen",
        "user_mail":"praveen@gmail.com",
        "user_Number":8220123333,
        "user_batchNO":"WE3",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":14,
        "user_name":"sibi",
        "user_mail":"sibi@gmail.com",
        "user_Number":8220123444,
        "user_batchNO":"WE4",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":15,
        "user_name":"sibisaveen",
        "user_mail":"sibisaveen@gmail.com",
        "user_Number":8220123555,
        "user_batchNO":"WE5",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":16,
        "user_name":"ruth",
        "user_mail":"ruth@gmail.com",
        "user_Number":8220123666,
        "user_batchNO":"WE6",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":17,
        "user_name":"santh",
        "user_mail":"santh@gmail.com",
        "user_Number":8220123777,
        "user_batchNO":"WE7",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":18,
        "user_name":"azhar",
        "user_mail":"azhar@gmail.com",
        "user_Number":8220123888,
        "user_batchNO":"WE8",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":19,
        "user_name":"ben",
        "user_mail":"ben@gmail.com",
        "user_Number":8220123999,
        "user_batchNO":"WE9",
        "mentor_id":1,
        "mentor_name": "sathish",
    },
    {
        "user_id":20,
        "user_name":"ruthsaveen",
        "user_mail":"ruthsaveen@gmail.com",
        "user_Number":8220123000,
        "user_batchNO":"WE10",
        "mentor_id":1,
        "mentor_name": "sathish",
    },


 ])